### ISSUE TITLE
Explosive Play & Explosive Elimination Notes

### ISSUE THREAD

**Issue by waweiwoowu** [iamwhoiamhahaha/hanabi#8]
* Example:
  * Alice has a known blue 5 and an unknown blue card.
  * Bob draws a blue 4.
  * Alice bombs the unknown blue card.
  * If it is a blue 3, Bob knows he just draws a blue 4. Then he blind-plays the blue 4 from slot 1.
  * If it is a blue 4, Bob also knows he just draws a blue 4. Then he marks the elimination notes on his slot 1 as a blue 4.

**Comment by waweiwoowu** [comment]
https://hanab.live/replay/331127/13

it's something like Explosive Redistribution

**Comment by Zamiell** [comment]
this is already the way we play, im not sure there is anything new here

**Comment by Zamiell** [comment]
also note that "Bob knows he just draws a blue 4." is *only* true if:
1) Alice discarded on the last goaround of the table
2) Bob discarded on the last goaround of the table
3) no emergency situations are going on

**Comment by waweiwoowu** [comment]
> this is already the way we play, im not sure there is anything new here

probably not a new convention but i dont believe you play with that lol
or maybe you misunderstood what i'm proposing
(btw, i was surprised you replied my 2p issue)

**Comment by waweiwoowu** [comment]
thanks for the note

**Comment by waweiwoowu** [comment]
### Explosive Play & Explosive Elimination Notes
- Normally, when a player has an unknown clued card in hand, they should write down all the possibilities of the clued cards and hold it until it is known to be playable.
- However, if the player can see their teammate has all the other copies of each possible card they have (except for the playable one), they are allow to play the unknown card as an *Explosive Play*.
- When this happens, their teammate should write down the *Elimination Notes* for each possibility (except for the playable one) in their entire hand.
- Example 1:
  - All the 1's are played on the stacks except for red 1 and blue 1.
  - Alice has an unknown 2 without any negative color information, i.e., it could be a red 2 or a blue 2.
  - Alice sees that Bob has a red 2 and a blue 2 in hand and plays her 2. It doesn't matter if it is playable.
  - Bob is surprised since Alice might misplay the red 2 or the blue 2 and the team would lose an important card. The reason why Alice can do this is because she can see the other copies of the cards she might be playing.
  - Therefore, Bob marks his hand with elimination notes for red 2 and blue 2.
- Example 2:
  - Red 2 is played on the stacks.
  - Alice has an unknown red card in hand.
  - Alice sees that Bob has a red 4 and a red 3 in hand and plays her red card. It doesn't matter if it is playable.
  - Bob is surprised since Alice might misplay the red 4 or the red 5 and the team would lose an important card. The reason why Alice can do this is because she can see the other copies of the cards she might be playing.
  - Therefore, Bob marks his hand with elimination notes for red 4 and red 5.

**Comment by waweiwoowu** [comment]
done
